"""Wiring centralizado para registrar rutas de chat desde main."""

from functools import partial
import uuid


def register_chat_routes_from_namespace(g):
    g["_register_chat_routes_core"](
        app=g["app"],
        login_required=g["login_required"],
        current_user=g["current_user"],
        email_re=g["EMAIL_RE"],
        new_chat_for_user_fn=partial(
            g["_new_chat_for_user_core"],
            db_session=g["db"].session,
        ),
        delete_chat_for_user_fn=lambda user_id, chat_id: g["_delete_chat_for_user_core"](
            user_id=user_id,
            chat_id=chat_id,
            db_session=g["db"].session,
            log_event_fn=g["log_event"],
        ),
        delete_chat_info_for_user_fn=lambda user_id, chat_id: g["_delete_chat_info_for_user_core"](
            user_id=user_id,
            chat_id=chat_id,
            db_session=g["db"].session,
            utcnow_naive_fn=g["utcnow_naive"],
        ),
        rename_chat_for_user_fn=lambda user_id, chat_id, raw_title: g["_rename_chat_for_user_core"](
            user_id=user_id,
            chat_id=chat_id,
            raw_title=raw_title,
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            db_session=g["db"].session,
            log_event_fn=g["log_event"],
        ),
        create_share_link_action_fn=lambda user_id, chat_id, permissions: g["_create_share_link_action_core"](
            user_id=user_id,
            chat_id=chat_id,
            permissions=permissions,
            db_session=g["db"].session,
            bool_flag_fn=g["_bool_flag"],
            token_factory_fn=lambda: uuid.uuid4().hex + uuid.uuid4().hex[:8],
            url_for_fn=g["url_for"],
        ),
        get_shared_context_fn=lambda token: g["_get_shared_context_core"](token=token, db_session=g["db"].session),
        resolve_viewer_name_fn=lambda email: g["_resolve_viewer_name_core"](email=email, db_session=g["db"].session),
        touch_shared_viewer_fn=lambda token, email, name: g["_touch_shared_viewer_core"](
            token=token,
            email=email,
            name=name,
            utcnow_naive_fn=g["utcnow_naive"],
        ),
        list_chat_history_fn=g["_list_chat_history_core"],
        shared_permissions_dict_fn=g["_shared_permissions_dict_core"],
        shared_viewer_count_fn=lambda token: g["_shared_viewer_count_core"](token=token, utcnow_naive_fn=g["utcnow_naive"]),
        shared_presence_action_fn=lambda token, viewer_email, viewer_name: g["_shared_presence_action_core"](
            token=token,
            viewer_email=viewer_email,
            viewer_name=viewer_name,
            touch_shared_viewer_fn=lambda tk, em, nm: g["_touch_shared_viewer_core"](
                token=tk,
                email=em,
                name=nm,
                utcnow_naive_fn=g["utcnow_naive"],
            ),
            shared_viewer_count_fn=lambda tk: g["_shared_viewer_count_core"](token=tk, utcnow_naive_fn=g["utcnow_naive"]),
        ),
        shared_logout_action_fn=lambda token, viewer_email: g["_shared_logout_action_core"](
            token=token,
            viewer_email=viewer_email,
            db_session=g["db"].session,
        ),
        shared_export_action_fn=lambda token, viewer_email, viewer_name: g["_shared_export_action_core"](
            token=token,
            viewer_email=viewer_email,
            viewer_name=viewer_name,
            db_session=g["db"].session,
        ),
        shared_send_action_fn=lambda token, viewer_email, viewer_name, message_raw, study_mode_raw, image_file: g["_shared_send_action_core"](
            token=token,
            viewer_email=viewer_email,
            viewer_name=viewer_name,
            message_raw=message_raw,
            study_mode_raw=study_mode_raw,
            image_file=image_file,
            db_session=g["db"].session,
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            generate_ai_response_fn=g["_generate_ai_response"],
            process_image_upload_fn=g["_process_shared_image_upload"],
            log_event_fn=g["log_event"],
            logger_obj=g["logger"],
            chat_max_text_chars=g["CHAT_MAX_TEXT_CHARS"],
            chat_max_image_bytes=g["CHAT_MAX_IMAGE_BYTES"],
        ),
        shared_regenerate_action_fn=lambda token, viewer_email, payload: g["_shared_regenerate_action_core"](
            token=token,
            viewer_email=viewer_email,
            payload=payload,
            db_session=g["db"].session,
            extract_image_url_fn=g["_extract_image_url"],
            image_md_re=g["IMAGE_MD_RE"],
            load_image_from_message_content_fn=g["_load_image_from_message_content"],
            generate_ai_response_fn=g["_generate_ai_response"],
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            log_event_fn=g["log_event"],
            logger_obj=g["logger"],
        ),
        list_saved_messages_action_fn=g["_list_saved_messages_action_core"],
        create_saved_message_action_fn=lambda user_id, raw_text: g["_create_saved_message_action_core"](
            user_id=user_id,
            raw_text=raw_text,
            db_session=g["db"].session,
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            utcnow_naive_fn=g["utcnow_naive"],
            prune_saved_messages_fn=lambda uid, keep=g["SAVED_MAX_ITEMS_PER_USER"]: g["_prune_saved_messages_core"](user_id=uid, keep=keep),
        ),
        sync_saved_messages_action_fn=lambda user_id, items: g["_sync_saved_messages_action_core"](
            user_id=user_id,
            items=items,
            db_session=g["db"].session,
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            parse_client_iso_to_naive_utc_fn=lambda value: g["_parse_client_iso_to_naive_utc_core"](
                value=value,
                utcnow_naive_fn=g["utcnow_naive"],
                to_naive_utc_fn=g["to_naive_utc"],
            ),
            prune_saved_messages_fn=lambda uid, keep=g["SAVED_MAX_ITEMS_PER_USER"]: g["_prune_saved_messages_core"](user_id=uid, keep=keep),
        ),
        delete_saved_message_action_fn=lambda user_id, item_id: g["_delete_saved_message_action_core"](
            user_id=user_id,
            item_id=item_id,
            db_session=g["db"].session,
        ),
        clear_saved_messages_action_fn=lambda user_id: g["_clear_saved_messages_action_core"](
            user_id=user_id,
            db_session=g["db"].session,
        ),
        edit_and_resend_action_fn=lambda payload: g["_edit_and_resend_action_core"](
            user_id=g["current_user"].id,
            payload=payload,
            db_session=g["db"].session,
            chat_max_text_chars=g["CHAT_MAX_TEXT_CHARS"],
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            extract_image_url_fn=g["_extract_image_url"],
            image_md_re=g["IMAGE_MD_RE"],
            load_image_from_message_content_fn=g["_load_image_from_message_content"],
            generate_ai_response_fn=g["_generate_ai_response"],
            log_event_fn=g["log_event"],
            logger_obj=g["logger"],
        ),
        regenerate_response_action_fn=lambda payload: g["_regenerate_response_action_core"](
            user_id=g["current_user"].id,
            payload=payload,
            db_session=g["db"].session,
            extract_image_url_fn=g["_extract_image_url"],
            image_md_re=g["IMAGE_MD_RE"],
            load_image_from_message_content_fn=g["_load_image_from_message_content"],
            generate_ai_response_fn=g["_generate_ai_response"],
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            log_event_fn=g["log_event"],
            logger_obj=g["logger"],
        ),
        chat_action_fn=lambda: g["_chat_action_core"](
            current_user_id=g["current_user"].id,
            user_is_authenticated=g["current_user"].is_authenticated,
            message_raw=g["request"].form.get('message', ''),
            study_mode_raw=g["request"].form.get('study_mode', 'normal'),
            chat_id_raw=g["request"].form.get('chat_id'),
            image_file=g["request"].files.get('image'),
            lista_de_claves=g["LISTA_DE_CLAVES"],
            chat_max_text_chars=g["CHAT_MAX_TEXT_CHARS"],
            rate_limit_check_fn=g["rate_limit_check"],
            rl_key_fn=g["_rl_key"],
            get_client_ip_fn=g["get_client_ip"],
            chat_rl_max=g["CHAT_RL_MAX"],
            chat_rl_window_s=g["CHAT_RL_WINDOW_S"],
            chat_rl_block_s=g["CHAT_RL_BLOCK_S"],
            db_session=g["db"].session,
            sanitize_text_for_db_fn=g["_sanitize_text_for_db"],
            process_image_upload_fn=g["_process_main_chat_image_upload"],
            generate_ai_response_fn=g["_generate_ai_response"],
            log_event_fn=g["log_event"],
            build_learning_links_markdown_fn=g["_build_learning_links_markdown"],
            logger_obj=g["logger"],
            debug_print_fn=print,
        ),
    )
